"use server";
import { redirect } from "next/navigation";
import { clearSession, createSession, getSession } from "@/lib/auth";
import { authenticateStudent, createStudent, hasConflict, removeInterview, saveInterview } from "@/lib/db";
import type { InterviewInput } from "@/lib/types";
type State = { error?: string } | null;
function input(formData: FormData): InterviewInput { return { studentName: String(formData.get("studentName") || "").trim(), yearsOfExperience: String(formData.get("yearsOfExperience") || "").trim() || null, experienceType: String(formData.get("experienceType") || "Original"), interviewDate: String(formData.get("interviewDate") || ""), fromTime: String(formData.get("fromTime") || ""), toTime: String(formData.get("toTime") || ""), technology: String(formData.get("technology") || "").trim() || null, companyName: String(formData.get("companyName") || "").trim() || null, interviewType: String(formData.get("interviewType") || "ChatGPT"), contactNumber: String(formData.get("contactNumber") || "").trim() || null, interviewRound: String(formData.get("interviewRound") || "").trim() || null, status: String(formData.get("status") || "Scheduled") as InterviewInput["status"] }; }
function valid(data: InterviewInput) { return data.studentName && data.interviewDate && data.fromTime && data.toTime && data.fromTime < data.toTime; }
export async function login(_state: State, formData: FormData): Promise<State> { const email = String(formData.get("email") || "").trim(); const password = String(formData.get("password") || ""); if (email === process.env.ADMIN_USERNAME && password === process.env.ADMIN_PASSWORD) { await createSession({ role: "admin", name: "Administrator" }); redirect("/dashboard"); } const student = await authenticateStudent(email, password); if (!student) return { error: "Invalid email or password." }; await createSession({ role: "student", userId: student.id, name: student.name }); redirect("/dashboard"); }
export async function register(_state: State, formData: FormData): Promise<State> { const name = String(formData.get("name") || "").trim(); const email = String(formData.get("email") || "").trim(); const password = String(formData.get("password") || ""); const contact = String(formData.get("contactNumber") || "").trim(); if (!name || !/^\S+@\S+\.\S+$/.test(email)) return { error: "Enter your name and a valid email address." }; if (password.length < 8) return { error: "Password must be at least 8 characters." }; try { const student = await createStudent(name, email, password, contact); await createSession({ role: "student", userId: student.id, name: student.name }); } catch (error) { if (String(error).includes("unique")) return { error: "An account already exists for this email." }; return { error: "Unable to create your account. Please try again." }; } redirect("/dashboard"); }
export async function logout() { await clearSession(); redirect("/login"); }
export async function checkConflict(formData: FormData) { const session = await getSession(); if (!session) return { error: "Unauthorized" }; const data = input(formData); const id = Number(formData.get("id")) || undefined; if (!valid(data)) return { error: "Please complete the required fields and use a valid time range." }; return { conflict: session.role === "student" && session.userId ? await hasConflict(data, session.userId, id) : false }; }
export async function persistInterview(formData: FormData) { const session = await getSession(); if (!session) return { error: "Unauthorized" }; const data = input(formData); const id = Number(formData.get("id")) || undefined; if (!valid(data)) return { error: "Please complete the required fields and use a valid time range." }; const saved = await saveInterview(data, session, id); if (!saved) return { error: "Interview not found or you do not have permission to update it." }; return { success: id ? "Interview updated successfully." : "Interview scheduled successfully." }; }
export async function deleteInterview(id: number) { const session = await getSession(); if (!session) return { error: "Unauthorized" }; return (await removeInterview(id, session)) ? { success: "Interview deleted successfully." } : { error: "Interview not found or you do not have permission to delete it." }; }
