"use server";
import { redirect } from "next/navigation";
import { clearSession, createSession, getSession } from "@/lib/auth";
import { hasBookedSlot, removeInterview, saveInterview } from "@/lib/db";
import type { InterviewInput } from "@/lib/types";
type State = { error?: string } | null;
function input(formData: FormData): InterviewInput { return { studentName: String(formData.get("studentName") || "").trim(), yearsOfExperience: String(formData.get("yearsOfExperience") || "").trim() || null, experienceType: String(formData.get("experienceType") || "Original"), interviewDate: String(formData.get("interviewDate") || ""), fromTime: String(formData.get("fromTime") || ""), toTime: String(formData.get("toTime") || ""), technology: String(formData.get("technology") || "").trim() || null, companyName: String(formData.get("companyName") || "").trim() || null, interviewType: String(formData.get("interviewType") || "ChatGPT"), contactNumber: String(formData.get("contactNumber") || "").trim() || null, interviewRound: String(formData.get("interviewRound") || "").trim() || null, status: String(formData.get("status") || "Scheduled") as InterviewInput["status"] }; }
function valid(data: InterviewInput) { return data.studentName && data.interviewDate && data.fromTime && data.toTime && data.fromTime < data.toTime; }
export async function login(_state: State, formData: FormData): Promise<State> { const username = String(formData.get("email") || "").trim(); const password = String(formData.get("password") || ""); if (username !== process.env.ADMIN_USERNAME || password !== process.env.ADMIN_PASSWORD) return { error: "Invalid admin username or password." }; await createSession({ role: "admin", name: "Administrator" }); redirect("/dashboard"); }
export async function logout() { await clearSession(); redirect("/login"); }
export async function checkConflict(formData: FormData) { const session = await getSession(); if (!session || session.role !== "admin") return { error: "Unauthorized" }; const data = input(formData); if (!valid(data)) return { error: "Please complete the required fields and use a valid time range." }; return { conflict: false }; }
export async function persistInterview(formData: FormData) { const session = await getSession(); if (!session || session.role !== "admin") return { error: "Unauthorized" }; const data = input(formData); const id = Number(formData.get("id")) || undefined; if (!valid(data)) return { error: "Please complete the required fields and use a valid time range." }; const saved = await saveInterview(data, session, id); if (!saved) return { error: "Interview not found or you do not have permission to update it." }; return { success: id ? "Interview updated successfully." : "Interview scheduled successfully." }; }
export async function scheduleInterview(formData: FormData) { const data = input(formData); if (!valid(data)) return { error: "Please complete the required fields and use a valid time range." }; if (await hasBookedSlot(data)) return { error: "Slot is already booked.", conflict: true }; await saveInterview(data, { role: "admin" }); return { success: "Your interview has been scheduled successfully." }; }
export async function deleteInterview(id: number) { const session = await getSession(); if (!session || session.role !== "admin") return { error: "Unauthorized" }; return (await removeInterview(id, session)) ? { success: "Interview deleted successfully." } : { error: "Interview not found or you do not have permission to delete it." }; }
