import { neon } from "@neondatabase/serverless";
import { pbkdf2Sync, randomBytes, timingSafeEqual } from "crypto";
import type { Interview, InterviewInput, Role, User } from "./types";
const sql = () => { if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not configured."); return neon(process.env.DATABASE_URL); };
let initialization: Promise<void> | undefined;
const selectColumns = `id, user_id AS "userId", student_name AS "studentName", years_of_experience::text AS "yearsOfExperience", experience_type AS "experienceType", to_char(interview_date, 'YYYY-MM-DD') AS "interviewDate", to_char(from_time, 'HH24:MI') AS "fromTime", to_char(to_time, 'HH24:MI') AS "toTime", technology, company_name AS "companyName", interview_type AS "interviewType", contact_number AS "contactNumber", interview_round AS "interviewRound", status`;
export async function initDatabase() { if (!initialization) initialization = (async () => { const q = sql(); await q`CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, contact_number TEXT, role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'admin')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`; await q`CREATE TABLE IF NOT EXISTS interviews (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, student_name TEXT NOT NULL, years_of_experience NUMERIC(5,2), experience_type TEXT NOT NULL, interview_date DATE NOT NULL, from_time TIME NOT NULL, to_time TIME NOT NULL, technology TEXT, company_name TEXT, interview_type TEXT NOT NULL, contact_number TEXT, interview_round TEXT, status TEXT NOT NULL DEFAULT 'Scheduled', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`; await q`ALTER TABLE interviews ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE CASCADE`; await q`CREATE INDEX IF NOT EXISTS interviews_user_date_idx ON interviews(user_id, interview_date)`; })().catch(e => { initialization = undefined; throw e; }); await initialization; }
function hashPassword(password: string) { const salt = randomBytes(16).toString("hex"); return `${salt}:${pbkdf2Sync(password, salt, 210000, 32, "sha256").toString("hex")}`; }
function validPassword(password: string, stored: string) { const [salt, hash] = stored.split(":"); if (!salt || !hash) return false; const candidate = pbkdf2Sync(password, salt, 210000, 32, "sha256").toString("hex"); return candidate.length === hash.length && timingSafeEqual(Buffer.from(candidate), Buffer.from(hash)); }
export async function createStudent(name: string, email: string, password: string, contactNumber = ""): Promise<User> { await initDatabase(); const rows = await sql()`INSERT INTO users (name,email,password_hash,contact_number,role) VALUES (${name},${email.toLowerCase()},${hashPassword(password)},${contactNumber || null},'student') RETURNING id,name,email,contact_number AS "contactNumber",role`; return rows[0] as User; }
export async function authenticateStudent(email: string, password: string): Promise<User | null> { await initDatabase(); const rows = await sql()`SELECT id,name,email,contact_number AS "contactNumber",role,password_hash AS "passwordHash" FROM users WHERE email=${email.toLowerCase()} AND role='student' LIMIT 1`; const user = rows[0] as (User & { passwordHash: string }) | undefined; return user && validPassword(password, user.passwordHash) ? user : null; }
export async function getStudent(id: number) { await initDatabase(); const rows = await sql()`SELECT id,name,email,contact_number AS "contactNumber",role FROM users WHERE id=${id} AND role='student'`; return (rows[0] as User | undefined) ?? null; }
export async function getInterviews(scope: { role: Role; userId?: number }, search = "", status = "All", dateFilter = "All", selectedDate = ""): Promise<Interview[]> { await initDatabase(); const term = `%${search}%`; const own = scope.role === "student" ? scope.userId ?? -1 : null; const q = sql(); const rows = await q.query(`SELECT ${selectColumns} FROM interviews WHERE ($1::int IS NULL OR user_id=$1) AND ($2='' OR student_name ILIKE $3 OR company_name ILIKE $3 OR technology ILIKE $3 OR contact_number ILIKE $3) AND ($4='All' OR status=$4) AND ($5='All' OR ($5='Today' AND interview_date=CURRENT_DATE) OR ($5='Yesterday' AND interview_date=CURRENT_DATE-INTERVAL '1 day') OR ($5='Tomorrow' AND interview_date=CURRENT_DATE+INTERVAL '1 day') OR ($5='Date' AND interview_date=NULLIF($6,'')::date)) ORDER BY interview_date ASC, from_time ASC`, [own, search, term, status, dateFilter, selectedDate]); return rows as Interview[]; }
export async function getInterview(id: number, scope: { role: Role; userId?: number }) { return (await getInterviews(scope)).find(x => x.id === id) ?? null; }
export async function getCounts(scope: { role: Role; userId?: number }) { const all = await getInterviews(scope); const today = new Date().toISOString().slice(0,10); const current = new Date().toTimeString().slice(0,5); return { today: String(all.filter(x => x.interviewDate === today).length), upcoming: String(all.filter(x => x.interviewDate > today || (x.interviewDate === today && x.fromTime >= current)).length), completed: String(all.filter(x => x.status === "Completed").length), total: String(all.length) }; }
export async function getToday(scope: { role: Role; userId?: number }) { return (await getInterviews(scope, "", "All", "Today")).slice(0, 6); }
export async function getUpcoming(scope: { role: Role; userId?: number }, limit = 5) { const today = new Date().toISOString().slice(0,10); const current = new Date().toTimeString().slice(0,5); return (await getInterviews(scope)).filter(x => x.interviewDate > today || (x.interviewDate === today && x.fromTime >= current)).slice(0, limit); }
export async function saveInterview(data: InterviewInput, scope: { role: Role; userId?: number }, id?: number) { await initDatabase(); const q = sql(); if (id) { const rows = await q`UPDATE interviews SET student_name=${data.studentName},years_of_experience=${data.yearsOfExperience},experience_type=${data.experienceType},interview_date=${data.interviewDate},from_time=${data.fromTime},to_time=${data.toTime},technology=${data.technology},company_name=${data.companyName},interview_type=${data.interviewType},contact_number=${data.contactNumber},interview_round=${data.interviewRound},status=${data.status},updated_at=NOW() WHERE id=${id} AND (${scope.role === "admin"} OR user_id=${scope.userId ?? -1}) RETURNING id`; return rows.length ? id : null; } const owner = scope.role === "student" ? scope.userId ?? null : null; const rows = await q`INSERT INTO interviews (user_id,student_name,years_of_experience,experience_type,interview_date,from_time,to_time,technology,company_name,interview_type,contact_number,interview_round,status) VALUES (${owner},${data.studentName},${data.yearsOfExperience},${data.experienceType},${data.interviewDate},${data.fromTime},${data.toTime},${data.technology},${data.companyName},${data.interviewType},${data.contactNumber},${data.interviewRound},${data.status}) RETURNING id`; return (rows[0] as { id: number }).id; }
export async function removeInterview(id: number, scope: { role: Role; userId?: number }) { await initDatabase(); const rows = await sql()`DELETE FROM interviews WHERE id=${id} AND (${scope.role === "admin"} OR user_id=${scope.userId ?? -1}) RETURNING id`; return rows.length > 0; }
export async function hasConflict(data: Pick<InterviewInput,"interviewDate"|"fromTime"|"toTime">, userId: number, ignoreId?: number) { await initDatabase(); const rows = await sql()`SELECT id FROM interviews WHERE user_id=${userId} AND interview_date=${data.interviewDate} AND from_time < ${data.toTime}::time AND to_time > ${data.fromTime}::time AND (${ignoreId ?? 0}=0 OR id!=${ignoreId ?? 0}) LIMIT 1`; return rows.length > 0; }
